// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectivityTestService 连通性测试服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAllResults 获取所有平台的测试结果
 */
export function GetAllResults(): $CancellablePromise<{ [_: string]: $models.ConnectivityResult[] }> {
    return $Call.ByID(3449037820).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAutoTestEnabled 获取自动测试开关状态
 */
export function GetAutoTestEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(1127144277);
}

/**
 * GetResults 获取指定平台的测试结果
 */
export function GetResults(platform: string): $CancellablePromise<$models.ConnectivityResult[]> {
    return $Call.ByID(3435021955, platform).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RunSingleTest 手动触发单个供应商测试
 */
export function RunSingleTest(platform: string, providerID: number): $CancellablePromise<$models.ConnectivityResult | null> {
    return $Call.ByID(2760516326, platform, providerID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetAutoTestEnabled 设置自动测试开关
 */
export function SetAutoTestEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2902580409, enabled);
}

/**
 * Wails 生命周期方法
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2984384939);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3083354649);
}

/**
 * TestAll 测试指定平台的所有启用检测的供应商
 */
export function TestAll(platform: string): $CancellablePromise<$models.ConnectivityResult[]> {
    return $Call.ByID(2959472920, platform).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * TestProvider 测试单个供应商连通性
 */
export function TestProvider(provider: $models.Provider, platform: string): $CancellablePromise<$models.ConnectivityResult | null> {
    return $Call.ByID(3468595208, provider, platform).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * TestProviderManual 手动测试供应商连通性（供前端测试按钮调用）
 */
export function TestProviderManual(platform: string, apiURL: string, apiKey: string, model: string, endpoint: string, authType: string): $CancellablePromise<$models.ManualTestResult> {
    return $Call.ByID(2146278070, platform, apiURL, apiKey, model, endpoint, authType).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConnectivityResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = $models.ManualTestResult.createFrom;
