// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HealthCheckService 健康检查服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanupOldRecords 清理过期的历史记录（保留最近 N 天）
 */
export function CleanupOldRecords(daysToKeep: number): $CancellablePromise<number> {
    return $Call.ByID(1926868227, daysToKeep);
}

/**
 * GetHistory 获取单个 Provider 的历史记录
 */
export function GetHistory(platform: string, providerName: string, limit: number): $CancellablePromise<$models.HealthCheckHistory | null> {
    return $Call.ByID(206722962, platform, providerName, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLatestResults 获取所有 Provider 的最新状态（按平台分组）
 * 优化：使用批量查询避免 N+1 查询问题
 */
export function GetLatestResults(): $CancellablePromise<{ [_: string]: $models.ProviderTimeline[] }> {
    return $Call.ByID(2783106257).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * IsPollingRunning 检查后台巡检是否运行中
 */
export function IsPollingRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1929693692);
}

/**
 * RunAllChecks 手动触发全部检测
 */
export function RunAllChecks(): $CancellablePromise<{ [_: string]: $models.HealthCheckResult[] }> {
    return $Call.ByID(1213979995).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * RunSingleCheck 手动触发单个 Provider 检测
 */
export function RunSingleCheck(platform: string, providerID: number): $CancellablePromise<$models.HealthCheckResult | null> {
    return $Call.ByID(2699783241, platform, providerID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SaveAvailabilityConfig 保存 Provider 的可用性高级配置
 */
export function SaveAvailabilityConfig(platform: string, providerID: number, config: $models.AvailabilityConfig | null): $CancellablePromise<void> {
    return $Call.ByID(1439140898, platform, providerID, config);
}

/**
 * SetAutoAvailabilityPolling 设置是否自动轮询（立即生效）
 */
export function SetAutoAvailabilityPolling(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2884686045, enabled);
}

/**
 * SetAvailabilityMonitorEnabled 启用/禁用指定 Provider 的可用性监控
 */
export function SetAvailabilityMonitorEnabled(platform: string, providerID: number, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3963090830, platform, providerID, enabled);
}

/**
 * SetConnectivityAutoBlacklist 启用/禁用指定 Provider 的连通性自动拉黑
 */
export function SetConnectivityAutoBlacklist(platform: string, providerID: number, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2480620645, platform, providerID, enabled);
}

/**
 * Start Wails 生命周期方法
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1052590838);
}

/**
 * StartBackgroundPolling 启动后台定时巡检
 */
export function StartBackgroundPolling(): $CancellablePromise<void> {
    return $Call.ByID(960209913);
}

/**
 * Stop Wails 生命周期方法
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(275484958);
}

/**
 * StopBackgroundPolling 停止后台巡检
 */
export function StopBackgroundPolling(): $CancellablePromise<void> {
    return $Call.ByID(2904570609);
}

// Private type creation functions
const $$createType0 = $models.HealthCheckHistory.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ProviderTimeline.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = $models.HealthCheckResult.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $$createType6);
const $$createType8 = $Create.Nullable($$createType5);
