// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddRepo(repo: $models.skillRepoConfig): $CancellablePromise<$models.skillRepoConfig[]> {
    return $Call.ByID(2020364064, repo).then(($result: any) => {
        return $$createType1($result);
    });
}

export function EnsureSkillLinks(): $CancellablePromise<void> {
    return $Call.ByID(1789465725);
}

/**
 * GetSkillContent 获取技能的 SKILL.md 内容
 */
export function GetSkillContent(directory: string): $CancellablePromise<string> {
    return $Call.ByID(3743777913, directory);
}

/**
 * GetSkillDiagnostics 返回 links/migrations/backups 的只读诊断数据。
 */
export function GetSkillDiagnostics(): $CancellablePromise<$models.SkillDiagnostics> {
    return $Call.ByID(428181056).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetSkillLinkStatus(): $CancellablePromise<$models.SkillLinkStatus> {
    return $Call.ByID(2399943974).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * InstallSkill installs a skill directory from the configured repositories.
 */
export function InstallSkill(directory: string, repoOwner: string, repoName: string, repoBranch: string): $CancellablePromise<void> {
    return $Call.ByID(2924128557, directory, repoOwner, repoName, repoBranch);
}

/**
 * ListAvailableSkills 返回远程 catalog 中可安装 skills。
 */
export function ListAvailableSkills(): $CancellablePromise<$models.Skill[]> {
    return $Call.ByID(2360640006).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListGroupedSkills 返回按来源仓库分组的 installed/available 数据。
 */
export function ListGroupedSkills(): $CancellablePromise<$models.GroupedSkills> {
    return $Call.ByID(3230213139).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListInstalledSkills 返回统一目录中的已安装 skills。
 */
export function ListInstalledSkills(): $CancellablePromise<$models.Skill[]> {
    return $Call.ByID(3887832687).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListRepos(): $CancellablePromise<$models.skillRepoConfig[]> {
    return $Call.ByID(1704737214).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListSkills 保持兼容，返回 installed + available 平铺结果。
 */
export function ListSkills(): $CancellablePromise<$models.Skill[]> {
    return $Call.ByID(3387382203).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OpenInstalledSkillFolder 打开已安装技能目录
 */
export function OpenInstalledSkillFolder(directory: string): $CancellablePromise<void> {
    return $Call.ByID(141351006, directory);
}

/**
 * OpenPlatformSkillsLink 打开平台 skills 入口；若链接不存在，则打开父目录。
 */
export function OpenPlatformSkillsLink(platform: string): $CancellablePromise<void> {
    return $Call.ByID(3203879100, platform);
}

/**
 * OpenSkillBackup 打开备份目录
 */
export function OpenSkillBackup(path: string): $CancellablePromise<void> {
    return $Call.ByID(2518967140, path);
}

/**
 * OpenUserSkillsFolder 打开统一技能目录
 */
export function OpenUserSkillsFolder(): $CancellablePromise<void> {
    return $Call.ByID(647422032);
}

export function RemoveRepo(owner: string, name: string): $CancellablePromise<$models.skillRepoConfig[]> {
    return $Call.ByID(2067147157, owner, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveSkillContent 保存技能的 SKILL.md 内容
 */
export function SaveSkillContent(directory: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3441672290, directory, content);
}

/**
 * Start 兼容旧调用方，实际 Wails v3 生命周期入口见 ServiceStartup。
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3921147663);
}

/**
 * Stop 兼容旧调用方。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(37757141);
}

/**
 * ToggleSkill 切换技能的启用状态
 * 通过修改 SKILL.md 的 disable-model-invocation 字段实现
 */
export function ToggleSkill(directory: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2154856646, directory, enabled);
}

export function UninstallSkill(directory: string): $CancellablePromise<void> {
    return $Call.ByID(3488362258, directory);
}

// Private type creation functions
const $$createType0 = $models.skillRepoConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SkillDiagnostics.createFrom;
const $$createType3 = $models.SkillLinkStatus.createFrom;
const $$createType4 = $models.Skill.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.GroupedSkills.createFrom;
